package org.tw.netbeans.project.switcher;

import org.openide.explorer.ExplorerManager;

/**
 *
 * @author toben
 */
public class ProjectChoicePanel extends javax.swing.JPanel implements ExplorerManager.Provider {

	/**
	 * Creates new form ProjectChoice
	 */
	public ProjectChoicePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceView1 = new org.openide.explorer.view.ChoiceView();

        setLayout(new java.awt.BorderLayout());
        add(choiceView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.ChoiceView choiceView1;
    // End of variables declaration//GEN-END:variables

	ExplorerManager manager = new ExplorerManager();
	
	@Override
	public ExplorerManager getExplorerManager() {
		return manager;
	}
}
