/*
 * #%L
 * project.switcher
 * %%
 * Copyright (C) 2013 - 2014 Toben
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 2.1 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public 
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */
package org.tw.netbeans.project.switcher;

import org.openide.explorer.ExplorerManager;

/**
 *
 * @author toben
 */
public class ProjectChoicePanel extends javax.swing.JPanel implements ExplorerManager.Provider {

	/**
	 * Creates new form ProjectChoice
	 */
	public ProjectChoicePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceView1 = new org.openide.explorer.view.ChoiceView();

        setLayout(new java.awt.BorderLayout());
        add(choiceView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.ChoiceView choiceView1;
    // End of variables declaration//GEN-END:variables

	ExplorerManager manager = new ExplorerManager();
	
	@Override
	public ExplorerManager getExplorerManager() {
		return manager;
	}
}
